### ISSUE TITLE
"Punch card" visualization of a boolean-valued plan

### ISSUE THREAD

**Issue by lostanlen** [mathieulagrange/doce#138]
inspired by Figure 2 of this paper

Weakly Supervised Source-Specific Sound Level Estimation in Noisy Soundscapes
Aurora Cramer, Mark Cartwright, Fatemeh Pishdadian, Juan Pablo Bello

https://arxiv.org/abs/2105.02911

**Comment by mathieulagrange** [comment]
punch card  with Na with demo with boolean factors

this must also be used for multipleplan and default values

**Comment by mathieulagrange** [comment]
![output](https://user-images.githubusercontent.com/12796829/173061537-12b114a2-62a3-44e1-a21b-4b01a58d2b61.png)

I think I came up with a reasonable solution

**Comment by lostanlen** [comment]
@mathieulagrange great work !! thank you 🙏🏻
