### ISSUE TITLE
Merge Plan Bug

### ISSUE THREAD

**Issue by rastegah** [mathieulagrange/doce#140]
when specifiying two plans the following error appears:

`Error: no-learn:feature is not a factor.`

**Comment by rastegah** [comment]
it will be very useful!

**Comment by mathieulagrange** [comment]
should be solved. You can play arround with the example multipleXpDemo

and cli such as 

python multipleXpDemo.py -s 1/method_methodTwo_parameterMethodTwo_1,method_methodTwo_parameterMethodTwo_3 -l
Plan xp2 is selected
method_methodTwo_parameterMethodTwo_1
method_methodTwo_parameterMethodTwo_3

python multipleXpDemo.py -l -s '1/[[0, 2], [0, 0]]'
Plan xp2 is selected
method_methodTwo_parameterMethodTwo_3
method_methodTwo_parameterMethodTwo_1

python multipleXpDemo.py -l -s 'xp2/[[0, 2], [0, 0]]'
Plan xp2 is selected
method_methodTwo_parameterMethodTwo_3
method_methodTwo_parameterMethodTwo_1
