### ISSUE TITLE
Warning raised when reduction operation of metrics is empty

### ISSUE THREAD

**Issue by pagrumiaux** [mathieulagrange/doce#153]
Displayed data generated from Thu Apr 14 15:21:26 2022 to Thu Apr 14 15:21:26 2022
/home/user/anaconda3/envs/bwe38/lib/python3.8/site-packages/doce/cli.py:341: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  dPercent = pd.Series([experiment._display.metricPrecision-2]*len(cPercent), index=cPercent)
/home/user/anaconda3/envs/bwe38/lib/python3.8/site-packages/doce/cli.py:343: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  dInt = pd.Series([0]*len(cInt), index=cInt)

**Comment by mathieulagrange** [comment]
I do not replicate on my side. This seems to be an casting issue. I tried to patch it. Can you check on your side ?
