### ISSUE TITLE
settings with '-' is saved as 'dash'

### ISSUE THREAD

**Issue by rastegah** [mathieulagrange/doce#158]
is there any reason that settings that contain an factor with '-' or '_' are saved as 'dash' and 'underscore'? it becomes quite confusing when retrieving settings

**Comment by mathieulagrange** [comment]
yes, it is not a bug it is a feature :)

I think it could be removed. let us discuss it !

**Comment by mathieulagrange** [comment]
this is now removed. 

Reading some docs about decently recent microsoft file systems, there seems to be no limitations in terms of multiple dot in filenames.

@rastegah beware that this will change the naming policy thus all computations will to be reruned or you will have to spend time renaming. I can help if needed.
