### ISSUE TITLE
TypeError: set() missing 1 required positional argument: 'args'

### ISSUE THREAD

**Issue by pagrumiaux** [mathieulagrange/doce#187]
I reinstalled doce today and had an error, 'args' is missing as an argument in the set() function. It worked in my previous installation

File "/home/grumiaux/miniconda3/envs/ddsp/lib/python3.8/site-packages/doce-0.2.dev0-py3.8.egg/doce/cli.py", line 252, in main
TypeError: set() missing 1 required positional argument: 'args'

**Comment by mathieulagrange** [comment]
are you running the most recent version ?

Is the example demo.py running smootlhy ?
