### ISSUE TITLE
Launching Doce experiments inside Python scripts

### ISSUE THREAD

**Issue by ax-le** [mathieulagrange/doce#215]
Hi!
This may be a naïve issue, so I apologize if the information was easily available.

I am opening this issue to understand how one could launch an experiment using only Python code, and not the CLI. In particular, I didn't find information in the documentation that such Python code is (conveniently) proposed to users.

To be extremely clear: is there a python version for "python3 my_doce_experiment.py -c" which could be coded inside a main? _(A python version that does not involve a workaround such as "os.system(python3 my_doce_experiment.py -c".)_

Thanks in advance!

**Comment by mathieulagrange** [comment]
checkout the new version on GitHub and look at the demo_nocli.py in the examples.

Is it doing what you need ?

**Comment by ax-le** [comment]
Yes it is, thanks!
Will you include the feature in the next release? It would help me a lot.
